services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    volumes:
      - ${SERVERS}/data/linkwarden/pgdata:/var/lib/postgresql/data
  linkwarden:
    container_name: linkwarden
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    build: . # uncomment to build from source
    # image: ghcr.io/linkwarden/linkwarden:latest # comment to build from source
    ports:
      - 3123:3000
    volumes:
      - ${SERVERS}/data/linkwarden/data:/data/data
    depends_on:
      - postgres
      - meilisearch
    labels:
      tsdproxy.enable: true
      tsdproxy.tlsvalidate: false
  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    restart: always
    env_file:
      - .env
    volumes:
      - ${SERVERS}/data/linkwarden/meili_data:/meili_data
